### ISSUE TITLE
File or directory not found [Waterfall] [1.13]

### ISSUE THREAD

**Issue by masagameplay** [masagameplay/MaSuiteCore#1]
```
[13:14:09] [main/WARN]: Exception encountered when loading plugin: MaSuiteCore
java.lang.RuntimeException: Unable to create configuration file
	at fi.matiaspaavilainen.masuitecore.config.Configuration.configChecker(Configuration.java:68) ~[?:?]
	at fi.matiaspaavilainen.masuitecore.config.Configuration.create(Configuration.java:40) ~[?:?]
	at fi.matiaspaavilainen.masuitecore.MaSuiteCore.onEnable(MaSuiteCore.java:16) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:261) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:555a3c3:216]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:283) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:555a3c3:216]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:555a3c3:216]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:555a3c3:216]
Caused by: java.io.IOException: Datei oder Verzeichnis nicht gefunden
	at java.io.UnixFileSystem.createFileExclusively(Native Method) ~[?:1.8.0_181]
	at java.io.File.createNewFile(File.java:1012) ~[?:1.8.0_181]
	at fi.matiaspaavilainen.masuitecore.config.Configuration.configChecker(Configuration.java:62) ~[?:?]
	... 6 more
```

**Comment by masagameplay** [comment]
The null bug is still there, work in progress.

**Comment by masagameplay** [comment]
So I found out that moving config generating to in it's own config file causes the problem. Fixed in https://github.com/masagameplay/MaSuiteCore/commit/95be88324aa798706d09ccd3c7e75e165f67e569
