### ISSUE TITLE
Home Function Error

### ISSUE THREAD

**Issue by williambacteria** [masagameplay/MaSuiteCore#18]
server version : 1.7.10
plugin version : the latest rewrite version
I set all permission for player ,but player cannot use home command:" I'm sorry, but there was an error performing this command."And server daemon crash as follows:
```
[02:34:39 ERROR]: Could not pass event PlayerMoveEvent to MaSuiteCore v2.0.0-SNAPSHOT
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-R0.1-SNAPSHOT]
        at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:344) [nh.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) [jd.class:?]
        at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(C03PacketPlayer.java:144) [je.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:176) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:989) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:458) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:806) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:665) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player$Spigot.sendMessage([Lnet/md_5/bungee/api/chat/BaseComponent;)V
        at dev.masa.masuitecore.bukkit.chat.Formator.sendMessage(Formator.java:36) ~[?:?]
        at dev.masa.masuitecore.core.services.WarmupService.onMove(WarmupService.java:100) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor98.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-R0.1-SNAPSHOT]
        ... 13 more
```
But when I'm op , I can use home commands without error and run well.

**Comment by masagameplay** [comment]
I think that 1.7.10 does not have all the features that MaSuite uses. Is there any specific reason why you are running 6 years old server version?

**Comment by williambacteria** [comment]
haha , I jsut wanna play some old mods on 1.7.10 . And I also run a 1.12.2 bungee server ,thanks for your answer ,I will solve it by myself.By the way, this is a nice plugin, thank you for your efforts!
