### ISSUE TITLE
Create Mysql Table Error

### ISSUE THREAD

**Issue by williambacteria** [masagameplay/MaSuiteCore#25]
Mysql Version:  5.7.26
Error ：

20:27:09 [信息] 2020-06-27 20:27:09,948 [DEBUG] DaoManager created dao for class class dev.masa.masuitecore.core.models.MaSuitePlayer with reflection
20:27:09 [信息] 2020-06-27 20:27:09,949 [INFO] TableUtils creating table 'masuite_players'
20:27:10 [信息] 2020-06-27 20:27:10,105 [DEBUG] JdbcPooledConnectionSource opened connection to jdbc:mysql://localhost:3304/masuite?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8 got #807322507
20:27:10 [信息] 2020-06-27 20:27:10,123 [DEBUG] JdbcPooledConnectionSource cache released connection #1858015030
20:27:10 [警告] Exception encountered when loading plugin: MaSuiteCore
java.sql.SQLException: SQL statement failed: CREATE TABLE IF NOT EXISTS `masuite_players` (`uuid` VARCHAR(48) , `username` VARCHAR(255) , `nickname` VARCHAR(255) , `firstLogin` BIGINT , `lastLogin` BIGINT , PRIMARY KEY (`uuid`) ) ENGINE=InnoDB
    at com.j256.ormlite.misc.SqlExceptionUtil.create(SqlExceptionUtil.java:25)
    at com.j256.ormlite.table.TableUtils.doStatements(TableUtils.java:423)
    at com.j256.ormlite.table.TableUtils.doCreateTable(TableUtils.java:399)
    at com.j256.ormlite.table.TableUtils.doCreateTable(TableUtils.java:383)
    at com.j256.ormlite.table.TableUtils.createTableIfNotExists(TableUtils.java:75)
    at dev.masa.masuitecore.core.services.PlayerService.<init>(PlayerService.java:27)
    at dev.masa.masuitecore.bungee.MaSuiteCore.onEnable(MaSuiteCore.java:51)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:250)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:286)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.sql.SQLException: Tablespace '`masuite`.`masuite_players`' exists.
    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912)
    at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1251)
    at com.j256.ormlite.jdbc.JdbcCompiledStatement.runExecute(JdbcCompiledStatement.java:71)
    at com.j256.ormlite.table.TableUtils.doStatements(TableUtils.java:417)
    ... 9 more

**Comment by williambacteria** [comment]
emm,nobody here ?

**Comment by masagameplay** [comment]
Have you exported/imported that table or database from somewhere else?

**Comment by williambacteria** [comment]
no,I just new to install this plugin in bungee

**Comment by CDFN** [comment]
Please paste logs on http://paste.lucko.me/, reading these logs is horrible.

**Comment by CDFN** [comment]
![image](https://user-images.githubusercontent.com/41289688/89108445-da109b80-d438-11ea-8f46-89dfd3a1ac60.png)
It seems statement above works fine - make sure you're running latest MySQL.
