### ISSUE TITLE
1.14 Error

### ISSUE THREAD

**Issue by 0xC1A551C** [masagameplay/MaSuiteCore#7]
```
 [00:36:45 ERROR]: Could not pass event InventoryCloseEvent to MaSuiteCore v1.5.5-SNAPSHOT
java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getName()Ljava/lang/String;
at fi.matiaspaavilainen.masuitecore.bukkit.gui.MaSuiteGUI$1.onClose(MaSuiteGUI.java:165) ~[?:?]
at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.14.jar:git-Paper-7]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.jar:git-Paper-7]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.jar:git-Paper-7]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:534) ~[patched_1.14.jar:git-Paper-7]
at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1316) ~[patched_1.14.jar:git-Paper-7]
at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:2114) ~[patched_1.14.jar:git-Paper-7]
at net.minecraft.server.v1_14_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:18) ~[patched_1.14.jar:git-Paper-7]
at net.minecraft.server.v1_14_R1.PacketPlayInCloseWindow.a(PacketPlayInCloseWindow.java:5) ~[patched_1.14.jar:git-Paper-7]
at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.jar:git-Paper-7]
at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.jar:git-Paper-7]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) ~[patched_1.14.jar:git-Paper-7]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.jar:git-Paper-7]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) ~[patched_1.14.jar:git-Paper-7]
at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:995) ~[patched_1.14.jar:git-Paper-7]
at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:988) ~[patched_1.14.jar:git-Paper-7]
at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(SourceFile:123) ~[patched_1.14.jar:git-Paper-7]
at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:972) ~[patched_1.14.jar:git-Paper-7]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:906) ~[patched_1.14.jar:git-Paper-7]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by masagameplay** [comment]
Fixed long time ago, forgot to close.
